name = "VLQuantitativeFinancePackage"
uuid = "4119e0bf-20d0-4785-913e-5ebdb0caa218"
authors = ["jdv27"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
